<?php /** @var $this Webguys_Easytemplate_Block_Template */ ?>

<iframe
    width="<?php echo $this->getTemplateVar('width'); ?>"
    height="<?php echo $this->getTemplateVar('height'); ?>"
    frameborder="0"
    scrolling="no"
    marginheight="0"
    marginwidth="0"
    src="https://www.google.de/maps?f=q&amp;source=s_q&amp;hl=de&amp;geocode=&amp;q=soest&amp;aq=&amp;sll=51.574508,8.07974&amp;sspn=0.261596,0.298004&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Soest,+Arnsberg,+Nordrhein-Westfalen&amp;ll=51.574509,8.079758&amp;spn=0.261616,0.298004&amp;z=12&amp;output=embed">
</iframe>

<?php if( $show_link = $this->getTemplateVar('show_link')) : ?>
    <br /><small><a href="<?php echo $this->getTemplateVar('map_url'); ?>" style="color:#0000FF;text-align:left"><?php echo $this->__('View Larger Map'); ?></a></small>
<?php endif; ?>