<?php /** @var $this Webguys_Easytemplate_Block_Template */ ?>

<?php

    preg_match('/< *iframe[^>]*src *= *["\']?([^"\']*)/i', $this->getData('map_url'), $iframe_matches);
    $iframeSrc = $iframe_matches[1];

    preg_match('/<small>(.*)<\/small>/isU', $this->getData('map_url'), $iframe_link);
    $link = $iframe_link[1];

?>

<iframe
    width="<?php echo $this->getData('width'); ?>"
    height="<?php echo $this->getData('height'); ?>"
    frameborder="0"
    scrolling="no"
    marginheight="0"
    marginwidth="0"
    src="<?php echo $iframeSrc; ?>">
</iframe>

<?php if( $show_link = $this->getData('show_link')) : ?>
    <br /><small><?php echo $link; ?></small>
<?php endif; ?>