<?php /** @var $this Webguys_Easytemplate_Block_Template */ ?>

<iframe
    width="<?php echo $this->getTemplateVar('width'); ?>"
    height="<?php echo $this->getTemplateVar('height'); ?>"
    frameborder="0"
    scrolling="no"
    marginheight="0"
    marginwidth="0"
    src="<?php echo $this->getTemplateVar('map_url'); ?>&amp;source=embed">
</iframe>

<?php if( $show_link = $this->getTemplateVar('show_link')) : ?>
    <br /><small><a href="<?php echo $this->getTemplateVar('map_url'); ?>" style="color:#0000FF;text-align:left"><?php echo $this->__('View Larger Map'); ?></a></small>
<?php endif; ?>