<?php /** @var $this Webguys_Easytemplate_Block_Template */ ?>

<?php if ($video_id = $this->getData('video_id')) : ?>
    <div class="et <?php echo $this->getTemplateCode() ?>">
        <iframe
            width="<?php echo $this->getData('width'); ?>"
            height="<?php echo $this->getData('height'); ?>"
            src="//www.youtube.com/embed/<?php echo $video_id; ?>?rel=0" 
            frameborder="0" 
            <?php if ((bool)$this->getData('allowfullscreen')) echo 'allowfullscreen=""'; ?>
        >
        </iframe>
    </div>
<?php endif; ?>