<?php /** @var $this Webguys_Easytemplate_Block_Adminhtml_Edit_Box */ ?>

<div class="template-box easytemplate" id="template_{{id}}">

    <div id="template_overview_{{id}}" class="template_overview f-left">

        <div class="information f-left">
            <div class="f-left">
                <span class="label"><?php echo Mage::helper('easytemplate')->__('Valid From') ?>:</span><br/>
                <span class="label"><?php echo Mage::helper('easytemplate')->__('Valid To') ?>:</span>
            </div>
            <div class="f-left">
                <span class="valid-from">{{valid_from}}</span><br/>
                <span class="valid-to">{{valid_to}}</span>
            </div>
            <br class="clear" />
        </div>

        <div class="information f-left">
            <div class="f-left">
                <span class="label"><?php echo Mage::helper('easytemplate')->__('Template Type') ?>:</span><br/>
                <span class="label"><?php echo Mage::helper('easytemplate')->__('Name') ?>:</span>
            </div>
            <div class="f-left">
                <span>{{label}}</span><br/>
                <span>{{name}}</span>
                <input type="hidden" name="template[{{id}}][code]" value="{{code}}"/>
            </div>
            <br style="clear:both"/>
        </div>
        <div class="information last f-right a-right">
            <?php echo $this->getOpenButton('{{id}}'); ?>
        </div>
        <br class="clear"/>
    </div>
    <br class="clear"/>

    <div id="template_content_{{id}}" class="template_container" style="display:none">
        <?php echo $this->getCloseButton('{{id}}', 'top'); ?>
        <input type="hidden" id="template_{{id}}_is_delete" name="template[{{id}}][is_delete]" value=""/>
        <input type="hidden" class="js-parentfield" id="template_{{id}}_id" name="template[{{id}}][id]" value="{{id}}"/>
        <input type="hidden" id="template_{{id}}_sort_order" name="template[{{id}}][sort_order]" value="{{position}}"/>
        <input type="hidden" id="template_{{id}}_parent_id" name="template[{{id}}][parent_id]" value="{{parent_id}}"/>
        <div class="template_content_status">
            <span class="label"><?php echo Mage::helper('easytemplate')->__('Active'); ?>:</span>
            <span class="desc"><input type="checkbox" name="template[{{id}}][active]" id="template_{{id}}_active" class="active-input" value="1" /></span>
            <span class="separator"></span>
            <span class="label"><?php echo Mage::helper('easytemplate')->__('Valid From') ?>:</span>
            <span class="desc"><input name="template[{{id}}][valid_from]" id="_valid_from_{{id}}" value="{{valid_from}}" type="text" class="datetime-input" style="width:70px;text-align:right"><img title="<?php echo Mage::helper('easytemplate')->__('Select date') ?>" id="_valid_from_{{id}}_trig" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>" class="v-middle" style="margin-left:3px;"></span>
            <span class="separator"></span>
            <span class="label"><?php echo Mage::helper('easytemplate')->__('Valid To') ?>:</span>
            <span clasS="desc"><input id="_valid_to_{{id}}" name="template[{{id}}][valid_to]" value="{{valid_to}}" type="text" class="datetime-input" style="width:70px;text-align:right"><img title="<?php echo Mage::helper('easytemplate')->__('Select date') ?>" id="_valid_to_{{id}}_trig" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/images/grid-cal.gif'; ?>" class="v-middle" style="margin-left:3px;"></span>
            <span class="separator"></span>
            <span class="label"><?php echo Mage::helper('easytemplate')->__('Name') ?></span>
            <span class="desc"><input type="text" class="required-entry input-text" id="template_{{id}}_name" name="template[{{id}}][name]" value="{{name}}" style="width:250px"></span>
        </div>
        <script type="text/javascript">
            //<![CDATA[
            Calendar.setup({
                inputField: '_valid_to_{{id}}',
                ifFormat: '<?php echo $this->getDateStrFormat() ?>',
                button: '_valid_to_{{id}}_trig',
                align: 'Bl',
                singleClick: true
            });
            Calendar.setup({
                inputField: '_valid_from_{{id}}',
                ifFormat: '<?php echo $this->getDateStrFormat() ?>',
                button: '_valid_from_{{id}}_trig',
                align: 'Bl',
                singleClick: true
            });

            if( '{{active}}' == 1 ){
                $('template_{{id}}_active').setAttribute('checked', true);
            }
            else {
                $('template_{{id}}').addClassName('inactive');
            }
            //]]>
        </script>
        <?php echo $this->getChildHtml('input'); ?>
        <div class="buttons">
            <?php echo $this->jsQuoteEscape($this->getDeleteButtonHtml()) ?>
            <?php echo $this->getCloseButton('{{id}}', 'bottom'); ?>
        </div>
    </div>
</div>