<div class="template-box" id="template_{{id}}">
    <table id="template_{{id}}_table" class="template-header" cellpadding="0" cellspacing="0">
        <input type="hidden" id="template_{{id}}_is_delete"
               name="template[{{id}}][is_delete]" value=""/>
        <input type="hidden" id="template_{{id}}_id"
               name="template[{{id}}][id]" value="{{id}}"/>
        <input type="hidden" id="template_{{id}}_sort_order"
               name="template[{{id}}][sort_order]" value="{{sort_order}}"/>
        <thead>
        <tr>
            <th class="tpl-title"><?php echo Mage::helper('easytemplate')->__('Name') ?>
                <span class="required">*</span>
            </th>
            <th class="tpl-type"><?php echo Mage::helper('easytemplate')->__('Template Type') ?>
                <span class="required">*</span>
            </th>
            <th class="tpl-order"><?php echo Mage::helper('easytemplate')->__('Sort Order') ?></th>
            <th class="a-right"><?php echo $this->jsQuoteEscape($this->getDeleteButtonHtml()) ?></th>
        </tr>
        </thead>
        <tr>
            <td><input type="text" class="required-entry input-text" id="template_{{id}}_name"
                       name="template[{{id}}][name]" value="{{name}}">
            </td>
            <td>
                <span>{{name}}</span>
                <input type="hidden" name="template[{{id}}][code]"
                       value="{{code}}"/></td>
            <td><input type="text" class="validate-zero-or-greater input-text"
                       name="template[{{id}}][sort_order]" value="{{position}}"></td>
            <td>&nbsp;</td>
        </tr>
    </table>

    <?php echo $this->getChildHtml('input'); ?>
</div>