<?php /** @var $this Webguys_Easytemplate_Block_Adminhtml_Edit_Renderer */ ?>

<script type="text/javascript">
//<![CDATA[
    templates['<?php echo $this->getBlockAlias() ?>'] = '<fieldset class="config"><table cellspacing="0" class="form-list"><colgroup class="label"></colgroup><colgroup class="value"></colgroup><colgroup class="comment"></colgroup><tbody><?php echo $this->getRendererHtml(); ?></tbody></table></fieldset>';
//]]>
</script>