<?php /** @var $this Webguys_Easytemplate_Block_Adminhtml_Edit_Selection */ ?>

<?php foreach( $this->getTemplates() AS $template) : ?>

    <div class="template-wrapper">

        <div class="title">
            <?php echo $template['label'] ?>
        </div>

        <?php if( is_array($template['items']) && count($template['items'])>0) : ?>

            <?php  foreach( $template['items'] AS $item) : ?>
                <div class="template">
                    <div class="title"><?php echo $item['label'] ?> </div>
                    <a onclick="easyTemplate.add('<?php echo $item['value']?>', '<?php echo $item['label']?>')">
                        <img src="<?php echo $this->getSkinUrl($item['image']) ?>" />
                    </a>
                </div>
            <?php endforeach; ?>

        <?php endif; ?>

    </div>

<?php endforeach; ?>