<?php /** @var $this Webguys_Easytemplate_Block_Adminhtml_Cms_Page_Edit_Tab_Templates_Template */ ?>

<script type="text/javascript">
//<![CDATA[
    var templates = new Array();
//]]>
</script>
<?php echo $this->getTemplatesHtml() ?>

<script type="text/javascript">
//<![CDATA[
var firstStepTemplate = '<div class="template-box" id="template_{{id}}">'+
    '<table id="<?php echo $this->getFieldId() ?>_{{id}}_table" class="template-header" cellpadding="0" cellspacing="0">'+
    '<input type="hidden" id="<?php echo $this->getFieldId() ?>_{{id}}_is_delete" name="<?php echo $this->getFieldName() ?>[{{id}}][is_delete]" value="" />'+
    '<input type="hidden" id="<?php echo $this->getFieldId() ?>_{{id}}_id" name="<?php echo $this->getFieldName() ?>[{{id}}][id]" value="{{id}}" />'+
    '<thead>'+
    '<tr>'+
    '<th class="tpl-title"><?php echo Mage::helper('easytemplate')->__('Name') ?> <span class="required">*</span></th>'+
    '<th class="tpl-type"><?php echo Mage::helper('easytemplate')->__('Template Type') ?> <span class="required">*</span></th>'+
    '<th class="tpl-order"><?php echo Mage::helper('easytemplate')->__('Sort Order') ?></th>'+
    '<th class="a-right"><?php echo $this->jsQuoteEscape($this->getDeleteButtonHtml()) ?></th>'+
    '</tr>'+
    '</thead>'+
    '<tr>'+
    '<td><input type="text" class="required-entry input-text" id="<?php echo $this->getFieldId() ?>_{{id}}_name" name="<?php echo $this->getFieldName() ?>[{{id}}][name]" value="{{title}}">{{checkboxScopeTitle}}</td>'+
    '<td> <span>{{template_name}}</span> <input type="hidden" name="<?php echo $this->getFieldName() ?>[{{id}}][code]" value="{{template_code}}" /> </td>'+
    '<td><input type="text" class="validate-zero-or-greater input-text" name="<?php echo $this->getFieldName() ?>[{{id}}][sort_order]" value="{{sort_order}}"></td>'+
    '<td>&nbsp;</td>'+
    '</tr></table></div>';

var pageTemplate = {
    div : $('page_templates_container_top'),
    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
    templateText : firstStepTemplate,
    itemCount : 1,
    add : function( code ) {
        this.template = new Template(this.templateText, this.templateSyntax);

        data = {};
        data.id  = 'new_' + this.itemCount;
        data.template_code = code;
        data.template_name = 'todo'; // TODO

        var selector_id = '<?php echo $this->getFieldId() ?>_' + data.id;

        Element.insert(this.div, {'after':this.template.evaluate(data)});

        this.itemCount++;
        this.bindRemoveButtons();

        if ( template = templates[code] ) {

            template = '<div id="'+selector_id+'_content" class="entry-edit">'+template+'</div>';
            this.secondTemplate = new Template(template, this.templateSyntax);

            Element.insert( selector_id +'_table', {'after':this.secondTemplate.evaluate(data)});

        }
        $('page_template_selector').hide();
    },
    remove : function(event){
        var element = $(Event.findElement(event, 'div'));
        if(element){
            $(element.readAttribute('id')+'_'+'is_delete').value = '1';
            element.addClassName('no-display');
            element.addClassName('ignore-validate');
            element.hide();
        }
    },
    bindRemoveButtons : function(){
        var buttons = $$('div.page-templates .delete-page-template');
        for(var i=0;i<buttons.length;i++){
            if(!$(buttons[i]).binded){
                $(buttons[i]).binded = true;
                Event.observe(buttons[i], 'click', this.remove.bind(this));
            }
        }
    }
}

pageTemplate.bindRemoveButtons();

//]]>
</script>

<div><?php if (!$this->isReadonly()):?><input type="hidden" name="affect_page_templates" value="1" /><?php endif;?></div>
