<?php /** @var $this Webguys_Easytemplate_Block_Input_Renderer_Divider */ ?>

<div class="divider template_field_divider_<?php echo $this->getCode() ?>">
    <?php if ($label = $this->getLabel()) : ?>
        <h1><?php echo $this->__($label) ?></h1>
    <?php endif; ?>

    <?php if ($comment = $this->getComment()) : ?>
        <p><?php echo $this->__($comment) ?></p>
    <?php endif; ?>
    <input id="template_field_{{id}}_<?php echo $this->getCode() ?>"
           name="template[{{id}}][fields][<?php echo $this->getCode() ?>]"
           value="1" type="hidden" />
</div>
