<?php /** @var $this Webguys_Easytemplate_Block_Input_Renderer_File */ ?>

<fieldset class="config">
    <table cellspacing="0" class="form-list">
        <colgroup class="label"></colgroup>
        <colgroup class="value"></colgroup>
        <colgroup class="comment"></colgroup>
        <tbody>
        <tr class="template_field_file_<?php echo $this->getCode() ?>">
            <td class="label">
                <label for="template_field_{{id}}_<?php echo $this->getCode() ?>"><?php echo $this->__(
                        $this->getLabel()
                    ) ?><?php if ($this->getRequired()) : ?> <span class="required">*</span><?php endif; ?></label>
            </td>
            <td class="value">
                <?php if ($this->hasFile()) : ?>

                    <?php if ($this->isImageFile())  : ?>

                        <a href="<?php echo $this->getFileUri() ?>"
                           onclick="imagePreview('template_field_{{id}}_file_<?php echo $this->getCode() ?>'); return false;">
                            <img src="<?php echo $this->getFileUri() ?>"
                                 id="template_field_{{id}}_file_<?php echo $this->getCode() ?>"
                                 title="<?php echo $this->escapeHtml($this->getValue()) ?>"
                                 alt="<?php echo $this->escapeHtml($this->getValue()) ?>" height="22" width="22"
                                 class="small-image-preview v-middle">
                        </a>

                    <?php else : ?>

                        <a href="<?php echo $this->getFileUri() ?>" target="_blank">
                            <?php echo $this->escapeHtml($this->getValue()) ?>
                        </a>

                    <?php endif; ?>

                <?php endif; ?>

                <input id="template_field_{{id}}_<?php echo $this->getCode() ?>"
                       name="template[{{id}}][fields][<?php echo $this->getCode() ?>]"
                       class="input-file<?php if ($this->getRequired() && !$this->hasFile()
                       ) : ?> required-entry<?php endif; ?>" type="file">
                <?php if ($this->hasFile()) : ?>
                    <span class="delete-image">
                    <input type="checkbox" name="template[{{id}}][fields][<?php echo $this->getCode() ?>][delete]"
                           value="1" class="checkbox" id="template_field_{{id}}_delete_<?php echo $this->getCode() ?>">
                    <label for="template_field_{{id}}_delete_<?php echo $this->getCode() ?>"> <?php echo $this->__(
                            'Delete File'
                        ) ?></label>
                    <input type="hidden" name="template[{{id}}][fields][<?php echo $this->getCode() ?>][existing]"
                           value="<?php echo $this->escapeHtml($this->getValue()) ?>">
                </span>
                <?php endif; ?>
            </td>
            <td class="comment">
                <?php echo $this->__($this->getComment()) ?>
            </td>
        </tr>
        </tbody>
    </table>
</fieldset>
