<?php /** @var $this Webguys_Easytemplate_Block_Input_Renderer_Text */ ?>


<fieldset class="config">
    <table cellspacing="0" class="form-list">
        <colgroup class="label"></colgroup>
        <colgroup class="value"></colgroup>
        <colgroup class="comment"></colgroup>
        <tbody>
            <tr class="template_field_text_<?php echo $this->getCode() ?>">
                <td class="label">
                    <label for="template_field_{{id}}_<?php echo $this->getCode() ?>"><?php echo $this->__($this->getLabel()) ?><?php if($this->getRequired()) : ?> <span class="required">*</span><?php endif; ?></label>
                </td>
                <td class="value">

                    <input id="template_field_{{id}}_<?php echo $this->getCode() ?>" name="template[{{id}}][fields][<?php echo $this->getCode() ?>]" value="<?php echo $this->getValue() ?>" class="input-text<?php if($this->getRequired()) : ?> required-entry<?php endif; ?>" type="text">
                    <button onclick="widgetTools.openDialog('<?php echo $this->getUrl('adminhtml/easytemplate_renderer_link/index', array( 'uniq_id' => 'template_field_{{id}}_'.$this->getCode() ) ) ?>')" class="scalable " type="button">
                        <span><span><span><?php echo $this->__('Please Select') ?></span></span></span>
                    </button>
                </td>
                <td class="comment">
                    <?php echo $this->__($this->getComment()) ?>
                </td>
            </tr>
        </tbody>
    </table>
</fieldset>
