<?php /** @var $this Webguys_Easytemplate_Block_Input_Renderer_Text */ ?>

<fieldset class="config">
    <table cellspacing="0" class="form-list">
        <colgroup class="label"></colgroup>
        <colgroup class="value"></colgroup>
        <colgroup class="comment"></colgroup>
        <tbody>

            <script type="text/javascript">
                var chooser_template_field_{{id}} = new WysiwygWidget.chooser(
                    'template_field_{{id}}',
                    null,
                    {}
                );
                var easytemplatechooser_{{id}} = new EasytemplateChooser( chooser_template_field_{{id}} , <?php echo json_encode( Mage::helper('easytemplate/chooser')->getInitChooserArray('template_field_{{id}}' ) ) ?> );
            </script>

            <tr class="template_field_text_<?php echo $this->getCode() ?>">
                <td class="label">
                    <label for="template_field_{{id}}"><?php echo $this->__($this->getLabel()) ?><?php if($this->getRequired()) : ?> <span class="required">*</span><?php endif; ?></label>
                </td>
                <td class="value">

                    <span id="template_field_{{id}}label"></span>

                    <select id="template_field_{{id}}typeselect">

                        <option value="product">
                            <?php echo $this->__('Product')?>
                        </option>
                        <option value="cms">
                            <?php echo $this->__('Pages')?>
                        </option>
                        <option value="category">
                            <?php echo $this->__('Category')?>
                        </option>

                    </select>

                    <input id="template_field_{{id}}value" name="template[{{id}}][fields][<?php echo $this->getCode() ?>]" value="<?php echo $this->getValue() ?>" class="input-text<?php if($this->getRequired()) : ?> required-entry<?php endif; ?>" type="text">
                    <button onclick="easytemplatechooser_{{id}}.open( $('template_field_{{id}}typeselect').value );" class="scalable" type="button">
                        <span><span><span><?php echo $this->__('Please Select') ?></span></span></span>
                    </button>
                </td>
                <td class="comment">
                    <?php echo $this->__($this->getComment()) ?>
                </td>
            </tr>
        </tbody>
    </table>
</fieldset>
