<?php /** @var $this Webguys_Easytemplate_Block_Input_Renderer_Multiselect */ ?>

<fieldset class="config">
    <table cellspacing="0" class="form-list">
        <colgroup class="label"></colgroup>
        <colgroup class="value"></colgroup>
        <colgroup class="comment"></colgroup>
        <tbody>
        <tr class="template_field_multiselect__<?php echo $this->getCode() ?>">
            <td class="label">
                <label for="template_field_{{id}}_<?php echo $this->getCode() ?>"><?php echo $this->__(
                        $this->getLabel()
                    ) ?><?php if ($this->getRequired()) : ?> <span class="required">*</span><?php endif; ?></label>
            </td>
            <td class="value">
                <select id="template_field_{{id}}_<?php echo $this->getCode() ?>"
                        name="template[{{id}}][fields][<?php echo $this->getCode() ?>][]"
                        class="select multiselect<?php if ($this->getRequired()) : ?> required-entry<?php endif; ?>"
                        size="10" multiple="multiple">
                    <?php foreach ($this->getOptionValues() as $value => $label) : ?>
                        <option value="<?php echo $value ?>"<?php if ($this->isSelected(
                            $value
                        )
                        ) : ?> selected="selected" <?php endif; ?>><?php echo $label ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td class="comment">
                <?php echo $this->__($this->getComment()) ?>
            </td>
        </tr>
        </tbody>
    </table>
</fieldset>
