<?php /** @var $this Webguys_Easytemplate_Block_Input_Renderer_Textarea */ ?>


<fieldset class="config">
    <table cellspacing="0" class="form-list">
        <colgroup class="label"></colgroup>
        <colgroup class="value"></colgroup>
        <colgroup class="comment"></colgroup>
        <tbody>
        <tr class="template_field_textarea_<?php echo $this->getCode() ?>">
            <td class="label">
                <label for="template_field_{{id}}_<?php echo $this->getCode() ?>"><?php echo $this->__(
                        $this->getLabel()
                    ) ?><?php if ($this->getRequired()) : ?> <span class="required">*</span><?php endif; ?></label>
            </td>
            <td class="value">
                <textarea id="template_field_{{id}}_<?php echo $this->getCode() ?>"
                          name="template[{{id}}][fields][<?php echo $this->getCode() ?>]"
                          class="textarea<?php if ($this->getRequired()) : ?> required-entry<?php endif; ?>" rows="2"
                          cols="15"><?php echo $this->escapeHtml($this->getValue()) ?></textarea>
            </td>
            <td class="comment">
                <?php echo $this->__($this->getComment()) ?>
            </td>
        </tr>
        </tbody>
    </table>
</fieldset>
