<?php /** @var $this Webguys_Easytemplate_Block_Input_Renderer_Textarea */ ?>

<tr class="template_field_textarea_<?php echo $this->getCode() ?>">
    <td class="label">
        <label for="template_field_{{template_id}}_<?php echo $this->getCode() ?>"><?php echo $this->__($this->getLabel()) ?><?php if($this->getRequired()) : ?> <span class="required">*</span><?php endif; ?></label>
    </td>
    <td class="value">
        <textarea id="template_field_{{template_id}}_<?php echo $this->getCode() ?>"
            name="templates[{{template_id}}][fields][<?php echo $this->getCode() ?>]" class="textarea<?php if($this->getRequired()) : ?> required-entry<?php endif; ?>" rows="2"
            cols="15"><?php echo $this->getDefault() ?></textarea>
    </td>
    <td class="comment">
        <?php echo $this->__($this->getComment()) ?>
    </td>
</tr>