<div class="gridster">
    <ul>
        <li data-row="1" data-col="1" data-sizex="2" data-sizey="2" data-max-sizex="2" data-max-sizey="6">
            0
            <br>
            <small>Overwrited to 2, 6</small>
        </li>
        <li data-row="1" data-col="3" data-sizex="1" data-sizey="2" data-max-sizex="6" data-max-sizey="2">
            1
            <br>
            <small>Overwrited max-size to 6, 2</small>
        </li>
        <li data-row="1" data-col="4" data-sizex="1" data-sizey="1">2</li>
        <li data-row="3" data-col="2" data-sizex="3" data-sizey="1">3</li>
        <li data-row="4" data-col="1" data-sizex="1" data-sizey="1">4</li>
        <li data-row="3" data-col="1" data-sizex="1" data-sizey="1">5</li>
        <li data-row="4" data-col="2" data-sizex="1" data-sizey="1">6</li>
        <li data-row="5" data-col="2" data-sizex="1" data-sizey="1">7</li>
        <li data-row="4" data-col="4" data-sizex="1" data-sizey="1">8</li>
        <li data-row="1" data-col="5" data-sizex="3" data-sizey="3" data-min-sizex="3" data-min-sizey="3">
            9
            <br>
            <small>Overwrited min-size to 3, 3</small>
        </li>
        <li data-row="5" data-col="1" data-sizex="1" data-sizey="2">10</li>
        <li data-row="4" data-col="3" data-sizex="1" data-sizey="2">11</li>
        <li data-row="5" data-col="4" data-sizex="1" data-sizey="1">12</li>
        <li data-row="6" data-col="2" data-sizex="3" data-sizey="1">13</li>
        <li data-row="4" data-col="5" data-sizex="1" data-sizey="2">14</li>
        <li data-row="6" data-col="5" data-sizex="1" data-sizey="1">15</li>
        <li data-row="7" data-col="3" data-sizex="1" data-sizey="1">16</li>
    </ul>
</div>

<script type="text/javascript">
    var gridster;

    require([
        "Webguys_Easytemplate/js/gridster"
    ], function () {

        gridster = jQuery(".gridster ul").gridster({
            widget_base_dimensions: [100, 55],
            widget_margins: [5, 5],
            helper: 'clone',
            resize: {
                enabled: true,
                max_size: [4, 4],
                min_size: [1, 1]
            }
        }).data('gridster');

    });

</script>