<?php /** @var $this \Webguys\Easytemplate\Block\Adminhtml\Page\Edit\Tab\Easytemplate */ ?>
<div class="gridster">
    <ul>
        <?php foreach ($this->getTemplates() AS $template) : ?>

            <?php $config = $template->getTemplateConfig(); ?>

            <li
                data-row="<?php echo $template->getRow(); ?>"
                data-col="<?php echo $template->getCol(); ?>"
                data-sizex="<?php echo $template->getSizex(); ?>"
                data-sizey="<?php echo $template->getSizey(); ?>"

                <?php if ($config) : ?>
                    data-min-sizex="<?php echo $config->getMinSizex() ?>"
                    data-min-sizey="<?php echo $config->getMinSizey() ?>"
                    data-max-sizex="<?php echo $config->getMaxSizex() ?>"
                    data-max-sizey="<?php echo $config->getMaxSizey() ?>"
                <?php endif; ?>

                >
                <div onclick="tobi_test(); return false;" style="cursor:pointer;">
                    <?php echo $template->getName(); ?>
                </div>
            </li>

        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
    var gridster;

    function tobi_test() {
        require([
            'jquery',
            'jquery/ui',
            'Magento_Ui/js/modal/modal'
        ], function ($) {
            $('<div />').html('TODO: Add and render fields here!')
                .modal({
                    type: 'slide',
                    title: 'Edit Template',
                    autoOpen: true,
                    buttons: [{
                        text: 'Confirm',
                        'class': 'action-primary',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                });
        });
    }

    require(["Webguys_Easytemplate/js/gridster"], function () {

        gridster = jQuery(".gridster ul").gridster({
            widget_margins: [5, 5],
            widget_base_dimensions: [jQuery('#page_tabs_easytemplate_section_content').width() / 12, 70],
            min_cols: 12,
            resize: {
                enabled: true
            }
        }).data('gridster');

    });

</script>