<?php /** @var $this \Webguys\Easytemplate\Block\Adminhtml\Page\Edit\Tab\Easytemplate */ ?>
<div class="gridster">
    <ul>
        <?php foreach ($this->getTemplates() AS $template) : ?>

            <?php $config = $template->getTemplateConfig(); ?>

            <li
                data-row="<?php echo $template->getRow(); ?>"
                data-col="<?php echo $template->getCol(); ?>"
                data-sizex="<?php echo $template->getSizex(); ?>"
                data-sizey="<?php echo $template->getSizey(); ?>"

                <?php if ($config) : ?>
                    data-min-sizex="<?php echo $config->getMinSizex() ?>"
                    data-min-sizey="<?php echo $config->getMinSizey() ?>"
                    data-max-sizex="<?php echo $config->getMaxSizex() ?>"
                    data-max-sizey="<?php echo $config->getMaxSizey() ?>"
                <?php endif; ?>

                >
                <div class="js-et-edit" data-et-edit-url="<?php echo $this->getUrl('easytemplate/template/view',array( 'id' => $template->getCode())) ?>">
                    <?php echo $template->getName(); ?>
                </div>
            </li>

        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
    require(["Webguys_Easytemplate/js/easytemplate"], function () {

        jQuery(".gridster ul").easytemplate();

    });

</script>