<?php /** @var $this \Webguys\Easytemplate\Block\Adminhtml\Template */ ?>
<?php if ($templateConfig = $this->getTemplateConfig()) : ?>

    <form class="<?php echo $templateConfig->getId(); ?>">

        <?php foreach ($templateConfig->getFields() AS $field) : ?>

            <div>
                <label>
                    <?php echo $field->getBackend()->getLabel(); ?>
                </label>

                <?php //$field->getBackend()->getInput()->toHtml(); ?>

                <input type="text" class=" input-text" value="ToDo" name="title"/>
            </div>

        <?php endforeach; ?>

    </form>

<?php else: ?>

    <p>
        <?php echo __('Template not found'); ?>
    </p>

<?php endif; ?>