<?php /** @var $this \Webguys\Easytemplate\Block\Adminhtml\Template */ ?>
<?php $templateConfig = $this->getTemplateConfig(); ?>

<form class="<?php echo $templateConfig->getId(); ?>">

    <?php foreach ($templateConfig->getFields() AS $field) : ?>

        <div>
            <label>
                <?php echo $field->getLabel(); ?>
            </label>

            <?php $field->getInputRenderer()->toHtml(); ?>

            <input type="text"
                   class=" input-text"
                   value="ToDo"
                   name="title"/>
        </div>

    <?php endforeach; ?>

</form>
